"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env")
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only-change-in-production",
)

DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

_allowed = os.environ.get("DJANGO_ALLOWED_HOSTS", "").strip()
if _allowed:
    ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()]
else:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

for _vercel_host in (
    (os.environ.get("VERCEL_URL") or "").strip(),
    (os.environ.get("VERCEL_BRANCH_URL") or "").strip(),
):
    if _vercel_host and _vercel_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_vercel_host)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'accounts',
    'hotelcrm',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'accounts.middleware.LicenseGateMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Vercel (serverless): uygulama dizini salt okunur → SQLite ile giriş/oturum yazılamaz
# ("attempt to write a readonly database"). Üretimde PostgreSQL kullanın.

_database_url = (os.environ.get("DATABASE_URL") or "").strip()
_on_vercel = (os.environ.get("VERCEL") or "").strip() == "1"

if _on_vercel and not _database_url:
    raise ImproperlyConfigured(
        "Vercel'de DATABASE_URL zorunlu (PostgreSQL). SQLite bu ortamda yazılamaz; "
        "ücretsiz seçenekler: Neon.tech veya Supabase. Bağlantıyı Vercel ortam "
        "değişkeni olarak ekleyin ve Build + Production'da tanımlı olsun."
    )

if _database_url:
    DATABASES = {
        "default": dj_database_url.parse(
            _database_url,
            conn_max_age=0,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# collectstatic (Vercel build) için gerekli
STATIC_ROOT = BASE_DIR / 'staticfiles'

# --- CORS ---
# Paketlenmiş Electron (başka PC) genelde Origin null/file → LAN testi için .env: DJANGO_CORS_ALLOW_ALL=1
_cors_allow_all = os.environ.get("DJANGO_CORS_ALLOW_ALL", "").strip().lower() in (
    "1",
    "true",
    "yes",
    "on",
)
_cors_extra = os.environ.get("DJANGO_CORS_EXTRA_ORIGINS", "").strip()
if _cors_allow_all:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = False
else:
    CORS_ALLOWED_ORIGINS = [
        "http://127.0.0.1:5173",
        "http://localhost:5173",
    ]
    for _u in _cors_extra.split(","):
        _u = _u.strip()
        if _u and _u not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(_u)
    CORS_ALLOW_CREDENTIALS = True

# --- DRF ---
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # Giriş/refresh herkese açık; korumalı endpoint’lerde view bazında IsAuthenticated kullanılır
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
}

# --- JWT ---

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# --- Merkez lisans (admin sunucusu) ---
# İkisi de doluysa her /api/* isteğinde merkez sorgulanır (kısa önbellek).
LICENSE_SERVER_URL = os.environ.get("LICENSE_SERVER_URL", "").strip().rstrip("/")
LICENSE_KEY = os.environ.get("LICENSE_KEY", "").strip()
_LICENSE_ENFORCE_RAW = os.environ.get("LICENSE_ENFORCE", "0").strip().lower()
LICENSE_ENFORCE = _LICENSE_ENFORCE_RAW in ("1", "true", "yes", "on")
# Panelden askıya alma vb. değişikliklerin otel API’sine yansıması için çok uzun tutmayın (örn. 120 yerine 25–60).
LICENSE_CHECK_CACHE_SECONDS = int(os.environ.get("LICENSE_CHECK_CACHE_SECONDS", "30"))
LICENSE_CHECK_TIMEOUT = float(os.environ.get("LICENSE_CHECK_TIMEOUT", "8"))
