# Generated by Django 5.0.6 on 2026-04-16 20:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrsSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chain_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=255)),
                ('from_label', models.CharField(blank=True, max_length=128)),
                ('to_label', models.CharField(blank=True, max_length=128)),
                ('guest_or_ref', models.CharField(blank=True, max_length=255)),
                ('outcome', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hotelcrm_crssynclog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('opened_on', models.DateField()),
                ('closed_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hotelcrm_folio',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('property_type', models.CharField(blank=True, max_length=32)),
                ('capacity_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hotelcrm_hotel',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'hotelcrm_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'hotelcrm_role',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('user_label', models.CharField(blank=True, max_length=128)),
                ('module', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotelcrm_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hotelcrm_auditlog',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='FolioLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_type', models.CharField(choices=[('accommodation', 'Accommodation'), ('extra', 'Extra'), ('tax', 'Tax'), ('payment', 'Payment')], max_length=32)),
                ('description', models.CharField(max_length=512)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('posted_date', models.DateField()),
                ('source_module', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hotelcrm.folio')),
            ],
            options={
                'db_table': 'hotelcrm_folioline',
            },
        ),
        migrations.CreateModel(
            name='GuestTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('direction', models.CharField(blank=True, max_length=16)),
                ('guest_name', models.CharField(max_length=255)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('flight_code', models.CharField(blank=True, max_length=32)),
                ('transfer_date', models.DateField()),
                ('transfer_time', models.TimeField(blank=True, null=True)),
                ('vehicle_label', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_transfers', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_guesttransfer',
            },
        ),
        migrations.CreateModel(
            name='GuestFeedbackEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=255)),
                ('room_number', models.CharField(blank=True, max_length=16)),
                ('score', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_feedback_entries', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_guestfeedbackentry',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=2)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('loyalty_tier', models.CharField(choices=[('None', 'None'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='None', max_length=16)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_visit_date', models.DateField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=32)),
                ('passport_no', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_guest',
            },
        ),
        migrations.CreateModel(
            name='GroupBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('leader_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('pax_total', models.PositiveIntegerField()),
                ('rooms_blocked', models.PositiveIntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('board_basis', models.CharField(blank=True, max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_bookings', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_groupbooking',
            },
        ),
        migrations.CreateModel(
            name='FoodWasteLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('item_description', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, max_length=128)),
                ('loss_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('waste_date', models.DateField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_waste_logs', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_foodwastelog',
            },
        ),
        migrations.CreateModel(
            name='EntertainmentShow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('show_date_label', models.CharField(blank=True, max_length=32)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entertainment_shows', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_entertainmentshow',
            },
        ),
        migrations.CreateModel(
            name='EntertainmentActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=128)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('day_label', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('participant_count', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entertainment_activities', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_entertainmentactivity',
            },
        ),
        migrations.CreateModel(
            name='DepartmentBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('department_name', models.CharField(max_length=255)),
                ('fiscal_year', models.PositiveIntegerField()),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_budgets', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_departmentbudget',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_department',
            },
        ),
        migrations.CreateModel(
            name='CommercialContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('partner_name', models.CharField(max_length=255)),
                ('contract_kind', models.CharField(blank=True, max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pricing_terms', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('review', 'Review'), ('expiring', 'Expiring'), ('ended', 'Ended')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_contracts', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_commercialcontract',
            },
        ),
        migrations.CreateModel(
            name='ChannelManagerSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_standard', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_deluxe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_suite', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_family', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stop_sale_single', models.BooleanField(default=False)),
                ('stop_sale_double', models.BooleanField(default=False)),
                ('stop_sale_triple', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_manager_settings', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_channelmanagersettings',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_channel',
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('flow_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=16)),
                ('description', models.CharField(max_length=512)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('credit_card', 'Credit card'), ('eft', 'EFT'), ('other', 'Other')], max_length=32)),
                ('tx_date', models.DateField()),
                ('tx_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_cashtransaction',
            },
        ),
        migrations.CreateModel(
            name='BanquetEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(blank=True, max_length=64)),
                ('hall_name', models.CharField(blank=True, max_length=128)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('pax', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banquet_events', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_banquetevent',
            },
        ),
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('integration_kind', models.CharField(blank=True, max_length=64)),
                ('connection_status', models.CharField(blank=True, max_length=16)),
                ('api_key_ref', models.CharField(blank=True, max_length=128)),
                ('last_sync_label', models.CharField(blank=True, max_length=64)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_connections', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_integrationconnection',
            },
        ),
        migrations.CreateModel(
            name='IntegrationEventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_code', models.CharField(blank=True, max_length=64)),
                ('event_type', models.CharField(blank=True, max_length=128)),
                ('outcome', models.CharField(blank=True, max_length=32)),
                ('meta', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='hotelcrm.integrationconnection')),
            ],
            options={
                'db_table': 'hotelcrm_integrationeventlog',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_inventoryitem',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('entry_date', models.DateField()),
                ('description', models.CharField(max_length=512)),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('account_code', models.CharField(blank=True, max_length=32)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_journalentry',
            },
        ),
        migrations.CreateModel(
            name='KvkkConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('guest_name', models.CharField(max_length=255)),
                ('consent_type', models.CharField(max_length=64)),
                ('consent_status', models.CharField(max_length=16)),
                ('record_date', models.DateField()),
                ('recorded_by', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kvkk_consents', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_kvkkconsent',
            },
        ),
        migrations.CreateModel(
            name='LaundryOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('guest_name', models.CharField(max_length=255)),
                ('order_date', models.DateField()),
                ('ordered_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('washing', 'Washing'), ('ready', 'Ready'), ('delivered', 'Delivered')], max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_orders', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_laundryorder',
            },
        ),
        migrations.CreateModel(
            name='LaundryPricelistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_pricelist_items', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_laundrypricelistitem',
            },
        ),
        migrations.CreateModel(
            name='LaundryOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_snapshot', models.CharField(max_length=128)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('laundry_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hotelcrm.laundryorder')),
                ('pricelist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='hotelcrm.laundrypricelistitem')),
            ],
            options={
                'db_table': 'hotelcrm_laundryorderline',
            },
        ),
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('location_found', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('found_date', models.DateField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('returned', 'Returned')], max_length=32)),
                ('returned_to_guest_name', models.CharField(blank=True, max_length=255)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_found_items', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_lostfounditem',
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('target_segment', models.CharField(blank=True, max_length=64)),
                ('accent_color', models.CharField(blank=True, max_length=16)),
                ('campaign_status', models.CharField(blank=True, max_length=16)),
                ('reservation_count', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaigns', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_marketingcampaign',
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_menucategory',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='hotelcrm.menucategory')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_menuitem',
            },
        ),
        migrations.CreateModel(
            name='MinibarCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('charge_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billed_to_folio', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minibar_charges', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_minibarcharge',
            },
        ),
        migrations.CreateModel(
            name='MinibarProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minibar_products', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_minibarproduct',
            },
        ),
        migrations.CreateModel(
            name='MinibarChargeLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_snapshot', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hotelcrm.minibarcharge')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='hotelcrm.minibarproduct')),
            ],
            options={
                'db_table': 'hotelcrm_minibarchargeline',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notif_type', models.CharField(blank=True, max_length=16)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationalInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=64, unique=True)),
                ('invoice_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('refund', 'Refund')], max_length=32)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('customer_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], max_length=16)),
                ('tax_id', models.CharField(blank=True, max_length=32)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_invoices', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_operationalinvoice',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('item_description', models.CharField(max_length=512)),
                ('supplier_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approval', 'Approval'), ('in_transit', 'In transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], max_length=32)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_purchaseorder',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('menu_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ingredients_text', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_recipe',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('primary_guest_name', models.CharField(max_length=255)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('nights', models.PositiveIntegerField()),
                ('adults', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('checked_in', 'Checked in'), ('checked_out', 'Checked out'), ('cancelled', 'Cancelled')], max_length=32)),
                ('board_basis', models.CharField(blank=True, choices=[('BB', 'BB'), ('HB', 'HB'), ('AI', 'AI')], max_length=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='hotelcrm.channel')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='hotelcrm.guest')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_reservation',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit card'), ('eft', 'EFT'), ('other', 'Other')], max_length=32)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('cash_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='hotelcrm.cashtransaction')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hotelcrm.reservation')),
            ],
            options={
                'db_table': 'hotelcrm_payment',
            },
        ),
        migrations.AddField(
            model_name='minibarcharge',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minibar_charges', to='hotelcrm.reservation'),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laundry_orders', to='hotelcrm.reservation'),
        ),
        migrations.CreateModel(
            name='KbsGuestSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField()),
                ('national_id', models.CharField(blank=True, max_length=32)),
                ('passport_no', models.CharField(blank=True, max_length=32)),
                ('nationality', models.CharField(blank=True, max_length=2)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kbs_submissions', to='hotelcrm.hotel')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kbs_submissions', to='hotelcrm.reservation')),
            ],
            options={
                'db_table': 'hotelcrm_kbsguestsubmission',
            },
        ),
        migrations.AddField(
            model_name='folio',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folio', to='hotelcrm.reservation'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='hotelcrm.reservation'),
        ),
        migrations.CreateModel(
            name='RestaurantOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('table_label', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed')], max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_date', models.DateField()),
                ('order_time', models.TimeField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_orders', to='hotelcrm.hotel')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_orders', to='hotelcrm.reservation')),
            ],
            options={
                'db_table': 'hotelcrm_restaurantorder',
            },
        ),
        migrations.CreateModel(
            name='RestaurantOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='hotelcrm.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hotelcrm.restaurantorder')),
            ],
            options={
                'db_table': 'hotelcrm_restaurantorderline',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=16)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('occupancy_status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('out_of_order', 'Out of order')], default='vacant', max_length=32)),
                ('clean_status', models.CharField(choices=[('clean', 'Clean'), ('dirty', 'Dirty')], default='clean', max_length=16)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_room',
            },
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_orders', to='hotelcrm.room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='hotelcrm.room'),
        ),
        migrations.AddField(
            model_name='minibarcharge',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minibar_charges', to='hotelcrm.room'),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_orders', to='hotelcrm.room'),
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('default_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_occupancy', models.PositiveIntegerField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_roomtype',
                'unique_together': {('hotel', 'code')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hotelcrm.roomtype'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_by_type', to='hotelcrm.roomtype'),
        ),
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('probability_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('new_lead', 'New lead'), ('meeting', 'Meeting'), ('proposal', 'Proposal'), ('won', 'Won'), ('lost', 'Lost')], max_length=32)),
                ('created_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_leads', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_saleslead',
            },
        ),
        migrations.CreateModel(
            name='SpaService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('default_therapist', models.CharField(blank=True, max_length=128)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_services', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_spaservice',
            },
        ),
        migrations.CreateModel(
            name='SpaAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('guest_name', models.CharField(max_length=255)),
                ('service_name_snapshot', models.CharField(max_length=255)),
                ('therapist_name', models.CharField(blank=True, max_length=128)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_appointments', to='hotelcrm.hotel')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spa_appointments', to='hotelcrm.reservation')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spa_appointments', to='hotelcrm.room')),
                ('spa_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='hotelcrm.spaservice')),
            ],
            options={
                'db_table': 'hotelcrm_spaappointment',
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=128)),
                ('shift_window', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On leave'), ('inactive', 'Inactive')], max_length=16)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('monthly_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='hotelcrm.department')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_staffmember',
            },
        ),
        migrations.CreateModel(
            name='OperationalTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('category', models.CharField(choices=[('housekeeping', 'Housekeeping'), ('technical', 'Technical')], max_length=32)),
                ('title', models.CharField(max_length=512)),
                ('priority', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_tasks', to='hotelcrm.hotel')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='hotelcrm.room')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='hotelcrm.staffmember')),
            ],
            options={
                'db_table': 'hotelcrm_operationaltask',
            },
        ),
        migrations.CreateModel(
            name='TourOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('tour_kind', models.CharField(blank=True, max_length=64)),
                ('guest_name', models.CharField(max_length=255)),
                ('tour_date', models.DateField()),
                ('pax', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_offers', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_touroffer',
            },
        ),
        migrations.CreateModel(
            name='TravelAgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('commission_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('agency_status', models.CharField(blank=True, max_length=16)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_agencies', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_travelagency',
            },
        ),
        migrations.CreateModel(
            name='AgencyPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('promo_status', models.CharField(blank=True, max_length=16)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='hotelcrm.travelagency')),
            ],
            options={
                'db_table': 'hotelcrm_agencypromotion',
            },
        ),
        migrations.CreateModel(
            name='AgencyContractRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('room_type_label', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('board_basis', models.CharField(blank=True, max_length=8)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_rates', to='hotelcrm.travelagency')),
            ],
            options={
                'db_table': 'hotelcrm_agencycontractrate',
            },
        ),
        migrations.CreateModel(
            name='GLAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('revenue', 'Revenue'), ('expense', 'Expense'), ('equity', 'Equity')], max_length=32)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_accounts', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_glaccount',
                'unique_together': {('hotel', 'code')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='hotelcrm.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_links', to='hotelcrm.role')),
            ],
            options={
                'db_table': 'hotelcrm_rolepermission',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hotel', 'room_number')},
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='hotelcrm.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotelcrm_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hotelcrm_userrole',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
