# Generated by Django 6.0.4 on 2026-04-16 22:06

import re

from django.db import migrations, models, transaction
from django.db.models import Q


def backfill_guest_display_codes(apps, schema_editor):
    Guest = apps.get_model("hotelcrm", "Guest")
    Hotel = apps.get_model("hotelcrm", "Hotel")
    qs = (
        Guest.objects.filter(hotel__isnull=False)
        .filter(Q(display_code__isnull=True) | Q(display_code=""))
        .order_by("created_at", "id")
    )
    for g in qs.iterator():
        with transaction.atomic():
            hotel = Hotel.objects.select_for_update().get(pk=g.hotel_id)
            hotel.guest_sequence += 1
            hotel.save(update_fields=["guest_sequence"])
            seq = hotel.guest_sequence
            base = re.sub(r"[^A-Z0-9]", "", (hotel.code or "").upper()) or "GUEST"
            Guest.objects.filter(pk=g.pk).update(display_code=f"{base}-{seq}")


def backfill_guest_display_codes_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='guest_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='display_code',
            field=models.CharField(blank=True, max_length=48, null=True, unique=True),
        ),
        migrations.RunPython(backfill_guest_display_codes, backfill_guest_display_codes_reverse),
    ]
