# Generated by Django 6.0.4 on 2026-04-17 12:33

import re

from django.db import migrations, models
from django.db.models import Q


def backfill_reservation_display_codes(apps, schema_editor):
    Hotel = apps.get_model("hotelcrm", "Hotel")
    Reservation = apps.get_model("hotelcrm", "Reservation")
    for hotel in Hotel.objects.all():
        seq = 0
        for res in (
            Reservation.objects.filter(hotel=hotel)
            .exclude(display_code__isnull=True)
            .exclude(display_code="")
        ):
            m = re.search(r"-R(\d+)$", res.display_code or "")
            if m:
                seq = max(seq, int(m.group(1)))
        qs = (
            Reservation.objects.filter(hotel=hotel)
            .filter(Q(display_code__isnull=True) | Q(display_code=""))
            .order_by("created_at")
        )
        base = re.sub(r"[^A-Z0-9]", "", (hotel.code or "").upper()) or "RES"
        for res in qs:
            seq += 1
            res.display_code = f"{base}-R{seq}"
            res.save(update_fields=["display_code"])
        hotel.reservation_sequence = seq
        hotel.save(update_fields=["reservation_sequence"])


def backfill_reservation_display_codes_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcrm', '0002_guest_display_code_and_hotel_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='reservation_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(
            backfill_reservation_display_codes,
            backfill_reservation_display_codes_reverse,
        ),
    ]
