# Generated by Django 6.0.4 on 2026-05-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcrm', '0007_reservationoccupant'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='bed_layout',
            field=models.CharField(blank=True, choices=[('unspecified', 'Belirtilmedi'), ('double_one', '1 çift kişilik'), ('twin_two', '2 tek kişilik (Twin)'), ('double_and_single', '1 çift + 1 tek'), ('two_double', '2 çift kişilik'), ('single_one', '1 tek kişilik')], default='unspecified', max_length=32),
        ),
    ]
