# Generated by Django 6.0.4 on 2026-05-06 20:34

from django.db import migrations, models


def copy_bed_layout_to_counts(apps, schema_editor):
    """Eski `bed_layout` seçimlerini sayısal alanlara taşır (görüntü özeti için)."""
    RoomType = apps.get_model('hotelcrm', 'RoomType')
    layout_map = {
        'double_one': (0, 1, 0),
        'twin_two': (2, 0, 0),
        'double_and_single': (1, 1, 0),
        'two_double': (0, 2, 0),
        'single_one': (1, 0, 0),
        'unspecified': (0, 0, 0),
    }
    for rt in RoomType.objects.all():
        key = (rt.bed_layout or '').strip() or 'unspecified'
        s, d, k = layout_map.get(key, (0, 0, 0))
        RoomType.objects.filter(pk=rt.pk).update(
            bed_single_count=s,
            bed_double_count=d,
            bed_king_count=k,
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcrm', '0008_roomtype_bed_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='bed_description',
            field=models.CharField(blank=True, default='', help_text='Ranza, yatalı şezlong, özel yapı vb. serbest tanım.', max_length=255),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='bed_double_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Çift kişilik (Queen / Full) yatak adedi.'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='bed_king_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='King ebatta çift kişilik yatak adedi.'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='bed_single_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Twin / tek kişilik yatak adedi.'),
        ),
        migrations.RunPython(copy_bed_layout_to_counts, noop),
    ]
