# Generated by Django 5.0.6 on 2026-05-12 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcrm', '0017_laundry_pricelist_module_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffabsencereport',
            options={'ordering': ['-absence_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='commercialcontract',
            name='auto_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commercialcontract',
            name='commercial_terms_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commercialcontract',
            name='governing_law',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='commercialcontract',
            name='partner_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commercialcontract',
            name='partner_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='commercialcontract',
            name='partner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='commercialcontract',
            name='partner_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='commercialcontract',
            name='partner_tax_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='commercialcontract',
            name='penalty_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commercialcontract',
            name='renewal_notice_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialcontract',
            name='signing_authority',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='commercialcontract',
            name='travel_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_contracts', to='hotelcrm.travelagency'),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='allotment_rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='cancellation_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='contact_title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='contract_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='contract_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='default_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='deposit_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='fax',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='iata_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='minimum_stay_nights',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='payment_method',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='payment_terms_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='postal_code',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='tax_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='tax_office',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='tursab_license_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='laundryorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('washing', 'Washing'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=32),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=32),
        ),
    ]
