# Generated by Django 5.0.6 on 2026-05-14 11:19

import django.db.models.deletion
import hotelcrm.models.staff
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcrm', '0023_hr_module_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffabsencereport',
            name='reason',
            field=models.CharField(choices=[('sick', 'Hastalık / rapor'), ('annual', 'Yıllık izin'), ('unexcused', 'Mazeretsiz devamsızlık'), ('excused', 'Mazeretli devamsızlık'), ('maternity', 'Doğum / analık izin'), ('bereavement', 'Ölüm izni'), ('unpaid_leave', 'Ücretsiz izin'), ('education', 'Eğitim / seminer (ücretli)'), ('military', 'Askerlik / idari izin'), ('other', 'Diğer')], max_length=32),
        ),
        migrations.CreateModel(
            name='HotelRecruitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=hotelcrm.models.staff._empty_recruitment_data)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_board', to='hotelcrm.hotel')),
            ],
            options={
                'db_table': 'hotelcrm_hotelrecruitment',
            },
        ),
    ]
