# Generated by Django 5.0.6 on 2026-05-17 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_inventory_lots(apps, schema_editor):
    InventoryItem = apps.get_model("hotelcrm", "InventoryItem")
    InventoryStockLot = apps.get_model("hotelcrm", "InventoryStockLot")
    for it in InventoryItem.objects.all().iterator():
        q = it.quantity_on_hand
        if q is None or q <= 0:
            continue
        InventoryStockLot.objects.create(
            hotel_id=it.hotel_id,
            item_id=it.id,
            quantity_initial=q,
            quantity_remaining=q,
            unit_cost=it.unit_cost,
            expiry_date=it.expiry_date,
            note="Migrasyon (tek parti)",
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcrm', '0029_staff_onboarding_it_hr_rbac'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Giriş / iade parti SKT (isteğe bağlı).', null=True),
        ),
        migrations.CreateModel(
            name='InventoryStockLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_initial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_remaining', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stock_lots', to='hotelcrm.hotel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lots', to='hotelcrm.inventoryitem')),
                ('source_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lots', to='hotelcrm.stockmovement')),
            ],
            options={
                'db_table': 'hotelcrm_inventorystocklot',
                'ordering': ['received_at', 'id'],
            },
        ),
        migrations.RunPython(backfill_inventory_lots, noop_reverse),
    ]
