# Generated by Django 6.0.5 on 2026-05-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcrm', '0030_inventory_stock_lots'),
        ('hotelcrm', '0032_audit_log_extended'),
    ]

    operations = [
    ]
