# Generated by Django 5.0.6 on 2026-05-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcrm', '0030_inventory_stock_lots'),
        ('hotelcrm', '0032_audit_log_extended'),
    ]

    operations = [
    ]
