# Generated by Django 6.0.5 on 2026-05-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcrm', '0033_merge_20260519_1929'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='hotelcrm_au_occurre_eb7e7e_idx',
            old_name='hotelcrm_au_occurre_0a8f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='hotelcrm_au_hotel_i_fd457e_idx',
            old_name='hotelcrm_au_hotel_i_4e2c91_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='hotelcrm_au_user_id_6945ba_idx',
            old_name='hotelcrm_au_user_id_7b3a44_idx',
        ),
        migrations.AlterField(
            model_name='hotelsurveysmssettings',
            name='public_base_url',
            field=models.URLField(blank=True, help_text='Misafirin anketi açacağı adres (örn. http://192.168.1.10:8000)', max_length=512),
        ),
        migrations.AlterField(
            model_name='hotelsurveysmssettings',
            name='sender_id',
            field=models.CharField(blank=True, help_text='Netgsm başlık / gönderen', max_length=32),
        ),
    ]
