# Generated by Django 6.0.4 on 2026-07-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcrm', '0033_merge_20260519_1630'),
        ('hotelcrm', '0035_hr_adjustments_module'),
    ]

    operations = [
    ]
